name: alpha_club
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^23.1.36
  dio: ^5.7.0
  # midtrans_sdk: ^0.4.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  intl: ^0.18.0
  flutter_markdown: ^0.7.5
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/